export { default as ClienteFormModal } from './ClienteFormModal.vue'
export { default as EmpleadoFormModal } from './EmpleadoFormModal.vue'
export { default as ServicioFormModal } from './ServicioFormModal.vue'
export { default as CitaFormModal } from './CitaFormModal.vue'
export { default as ProductoFormModal } from './ProductoFormModal.vue'
export { default as BranchFormModal } from './BranchFormModal.vue'
